"""mandatory

Revision ID: 8cc105ce27fb
Revises: 8671fc692299
Create Date: 2024-06-20 15:49:18.006594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc105ce27fb'
down_revision: Union[str, None] = '8671fc692299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parameters', 'value', existing_type=sa.String(length=255), nullable=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
